format_version = 1

[project]
name = "hello-ferron"
version = "0.1.0"

[scripts]
dir = "scripts"
entry = "MyGame.Main, MyGame"

[assets]
dir = "assets" #optional

[scenes]
start = "scenes/main.fscene" #optional