use std::sync::Arc;

use vulkano::buffer::{Buffer, BufferCreateInfo, BufferUsage};
use vulkano::command_buffer::{
    AutoCommandBufferBuilder, BlitImageInfo, CommandBufferUsage, CopyBufferToImageInfo, ImageBlit,
    PrimaryAutoCommandBuffer,
};
use vulkano::format::{Format, FormatFeatures};
use vulkano::image::sampler::Filter;
use vulkano::image::view::ImageView;
use vulkano::image::{
    Image, ImageCreateInfo, ImageSubresourceLayers, ImageType, ImageUsage, max_mip_levels,
    mip_level_extent,
};
use vulkano::memory::allocator::{AllocationCreateInfo, MemoryTypeFilter};
use vulkano::sync::{self, GpuFuture};

use super::context::VkContext;

pub(super) enum MipPolicy {
    /// One level. For data textures (noise, LUTs) and 1x1 fallbacks.
    None,
    /// Full chain, generated by a blit chain at upload.
    Generate,
}

/// Fills mip levels 1.. by successively halving level 0 with a linear blit.
/// Assumes level 0 is already populated and the image carries `TRANSFER_SRC`.
fn generate_mips(
    builder: &mut AutoCommandBufferBuilder<PrimaryAutoCommandBuffer>,
    image: &Arc<Image>,
) {
    let base = image.extent();
    let source_layers = image.subresource_layers();
    let aspects = source_layers.aspects;

    for level in 1..image.mip_levels() {
        let src_extent = mip_level_extent(base, level - 1).unwrap();
        let dst_extent = mip_level_extent(base, level).unwrap();

        let region = ImageBlit {
            src_subresource: ImageSubresourceLayers {
                aspects,
                mip_level: level - 1,
                array_layers: 0..1,
            },
            src_offsets: [[0, 0, 0], src_extent],
            dst_subresource: ImageSubresourceLayers {
                aspects,
                mip_level: level,
                array_layers: 0..1,
            },
            dst_offsets: [[0, 0, 0], dst_extent],
            ..Default::default()
        };

        builder
            .blit_image(BlitImageInfo {
                regions: vec![region].into(),
                filter: Filter::Linear,
                ..BlitImageInfo::images(image.clone(), image.clone())
            })
            .unwrap();
    }
}

// `format` chooses how the shader interprets the bytes (e.g. `R8G8B8A8_SRGB`
// for color, `R8G8B8A8_UNORM` for data maps).
pub(super) fn upload_texture(
    ctx: &VkContext,
    pixels: &[u8],
    extent: [u32; 2],
    format: Format,
    mips: MipPolicy,
) -> Arc<ImageView> {
    let physical = ctx.device.physical_device();

    let blittable = physical
        .format_properties(format)
        .unwrap()
        .optimal_tiling_features
        .contains(
            FormatFeatures::BLIT_SRC
                | FormatFeatures::BLIT_DST
                | FormatFeatures::SAMPLED_IMAGE_FILTER_LINEAR,
        );

    let full_chain = max_mip_levels([extent[0], extent[1], 1]);

    let mip_levels = match mips {
        MipPolicy::Generate if blittable => full_chain,
        _ => 1,
    };

    let staging = Buffer::from_iter(
        ctx.memory_allocator.clone(),
        BufferCreateInfo {
            usage: BufferUsage::TRANSFER_SRC,
            ..Default::default()
        },
        AllocationCreateInfo {
            memory_type_filter: MemoryTypeFilter::PREFER_HOST
                | MemoryTypeFilter::HOST_SEQUENTIAL_WRITE,
            ..Default::default()
        },
        pixels.iter().copied(),
    )
    .expect("failed to allocate texture staging buffer");

    let image = Image::new(
        ctx.memory_allocator.clone(),
        ImageCreateInfo {
            image_type: ImageType::Dim2d,
            format,
            extent: [extent[0], extent[1], 1],
            mip_levels,
            usage: ImageUsage::TRANSFER_DST | ImageUsage::SAMPLED | ImageUsage::TRANSFER_SRC,
            ..Default::default()
        },
        AllocationCreateInfo {
            memory_type_filter: MemoryTypeFilter::PREFER_DEVICE,
            ..Default::default()
        },
    )
    .expect("failed to create texture image");

    let mut builder = AutoCommandBufferBuilder::primary(
        ctx.command_buffer_allocator.clone(),
        ctx.queue.queue_family_index(),
        CommandBufferUsage::OneTimeSubmit,
    )
    .unwrap();
    builder
        .copy_buffer_to_image(CopyBufferToImageInfo::buffer_image(staging, image.clone()))
        .unwrap();

    if mip_levels > 1 {
        generate_mips(&mut builder, &image);
    }

    let command_buffer = builder.build().unwrap();

    sync::now(ctx.device.clone())
        .then_execute(ctx.queue.clone(), command_buffer)
        .unwrap()
        .then_signal_fence_and_flush()
        .unwrap()
        .wait(None)
        .unwrap();

    ImageView::new_default(image).expect("failed to create texture image view")
}
